version: '3.8'
services:
  mysqldb:
    build: ./mysql-dump
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
  web_immo:
    depends_on:
      - mysqldb
    build: ./web
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - data_immo:/www
    environment:
      - SQL_HOST=mysqldb
      - SQL_USER=$MYSQLDB_USER
      - SQL_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - SQL_DBNAME=$MYSQLDB_DATABASE
      - SQL_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
volumes:
  data_immo:
